### ISSUE TITLE
Footer Info

### ISSUE THREAD

**Issue by flipsum0** [qlcchain/QLCWallet#16]
Add footer with infos at the bottom of each page:

QLC CHAIN WALLET    |    VERSION 1.0.0    |    NETWORK: TESTNET
© 2018 QLC CHAIN    |    ABOUT    |    CONTACT US

Screenshot:
![footer](https://user-images.githubusercontent.com/35636290/44033519-e8504782-9f0a-11e8-9402-ed1b3b8d042f.png)

**Comment by gythialy** [comment]
fixed via 89939f929d02fb13940e4fc0dbbbfa1316d4b7d7
