### ISSUE TITLE
Accounts - Name Display Fix

### ISSUE THREAD

**Issue by flipsum0** [qlcchain/QLCWallet#18]
**Description**

Add a space (&nbsp;) between Account Name and Address on pages:
- Account Main
- Account Details

**Screenshot**

![account_display_add_space](https://user-images.githubusercontent.com/35636290/44035430-c7466bd4-9f0f-11e8-8ebe-aff319fb2f58.png)

![account_details_display_add_space](https://user-images.githubusercontent.com/35636290/44036954-699a2f76-9f13-11e8-87c5-9d139f63f851.png)

**Comment by gythialy** [comment]
fix via b10d0de0b93d88bc73d1a7a969f2c0ae87f69bb1
