### ISSUE TITLE
Menu - Notification for Pending Receive Transactions

### ISSUE THREAD

**Issue by flipsum0** [qlcchain/QLCWallet#19]
**Description**

1. Add notification badge to the "Receive" button in the menu displaying the number of new pending transactions that are waiting to be accepted
2. Add auto-refresh interval to update the badge

**Screenshot**

![menu_received_notification](https://user-images.githubusercontent.com/35636290/44036167-75b5643a-9f11-11e8-9790-aae7a561d72e.png)

**Comment by gythialy** [comment]
fixed via 89939f929d02fb13940e4fc0dbbbfa1316d4b7d7
