### ISSUE TITLE
Chinese version

### ISSUE THREAD

**Issue by txdzhang** [qlcchain/QLCWallet#2]
Add New Account 
添加>>>添加新账户

**Comment by ariesunny** [comment]
Could share a screen-shot of this error? @txdzhang

**Comment by txdzhang** [comment]
![image](https://user-images.githubusercontent.com/41662938/43693410-39c219f2-9960-11e8-932b-86d985c2f3ef.png)
should be 添加新账户

**Comment by ariesunny** [comment]
O, I See

**Comment by gythialy** [comment]
closed via 878639840b26fd98a431c4dfa04d413375a168ac
