### ISSUE TITLE
Recevie notification error

### ISSUE THREAD

**Issue by ariesunny** [qlcchain/QLCWallet#30]
**Describe the bug**
When new transaction coming, there is a notification on Receive Tab, the noficaiton shall be cleared after the receive block is generated, but it is not.

**To Reproduce**
1, Do a transaction
2, Check the notificaion flag
3, Click the "Receive" to accept the transaction
4, Check if the notification updated

**Expected behavior**
The notificaion flag shall be updated when receive block is generated.

**Screenshots**
![image](https://user-images.githubusercontent.com/30827440/51162951-05717b00-18d3-11e9-9aa5-bc0e7f8f22ad.png)

**Environment (please complete the following information):**
 - OS: Windows
 - Browser:Chrome

**Additional context**
Wallet V2.0.0 and Qlc node V0.0.2

**Comment by gythialy** [comment]
closed via 062b53b6adf15adf69a590bd231c4b4f26302b55
