### ISSUE TITLE
Error info output when do "Receive" action

### ISSUE THREAD

**Issue by ariesunny** [qlcchain/QLCWallet#31]
**Describe the bug**
There is an error info output when receiving action, but actually the receive block is genereated.

**To Reproduce**
1, Place a transaction.
2, Do receive and check.

**Expected behavior**
No error info
Or what does this error means?

**Screenshots**
![image](https://user-images.githubusercontent.com/30827440/51163269-166ebc00-18d4-11e9-8e7d-114d676df898.png)

**Environment (please complete the following information):**
 - OS: windows
 - Browser: Chrome

**Additional context**

**Comment by gythialy** [comment]
closed via 062b53b6adf15adf69a590bd231c4b4f26302b55
