### ISSUE TITLE
Defaut representative does not exist.

### ISSUE THREAD

**Issue by ariesunny** [qlcchain/QLCWallet#32]
**Describe the bug**
In Represnetative page and change represenatives, click a the contract flag in "New represenative" line, there is wallet rsp: qlc_1fgjjb6se11atyyij6xkkkxyhc1psbhdg7s6xau1d8hguz3miausjqfpxc8q, when I chose it and click the "Update Represenatives", it says the Represenatives does not exist.

**To Reproduce**
1. Go to Represenatives 
2, Click a the contract flag in "New represenative" line.
3, Chose the 2nd default represenative: qlc_1fgjjb6se11atyyij6xkkkxyhc1psbhdg7s6xau1d8hguz3miausjqfpxc8q
4, Click Update Represenatives

**Expected behavior**
If qlc_1fgjjb6se11atyyij6xkkkxyhc1psbhdg7s6xau1d8hguz3miausjqfpxc8q is not a valid represenative, do not show it. 
If it is valid, no this error

**Screenshots**
![image](https://user-images.githubusercontent.com/30827440/51163843-0fe14400-18d6-11e9-9613-6d5f24cf2440.png)

![image](https://user-images.githubusercontent.com/30827440/51163691-79148780-18d5-11e9-8b9e-81c379f7c2cc.png)

**Environment (please complete the following information):**
 - OS: Windows
 - Browser: Chrome

**Additional context**

**Comment by gythialy** [comment]
closed via 062b53b6adf15adf69a590bd231c4b4f26302b55
